### PR TITLE
fix: get CM tests working against OSLC RefImpl

### LINKED ISSUE #19: DefaultRequestHeaders overwritten
All the headers set before a GetResource call are wiped out. I cannot add my own headers

### PR DESCRIPTION
**Pull request by berezovskyi**
Quite a long list of things remains:

- [x] Re-enable all formats.
	- [x] Get RDF/XML tests to work against https://github.com/oslc-op/refimpl/tree/master/src/server-cm
	- [x] Get Turtle tests to work against https://github.com/oslc-op/refimpl/tree/master/src/server-cm. **Had to disable dotNetRDF IRI checks to make tests pass. Would be good to expose the option to the users.**
	- [x] Get raw XML (deprecated!) tests to work against https://github.com/oslc-op/refimpl/tree/master/src/server-cm
	- [ ] Get OSLC JSON (deprecated!) tests to work against https://github.com/oslc-op/refimpl/tree/master/src/server-cm
- [x] Stop overwriting HTTP client defaults for every request. See #19.
- [ ] Implement basic auth support – for now we disable the `CredentialsFilter` in the CM RefImpl server.
- [ ] Go over the Core/CM spec texts for the commented out asserts.
- [ ] Stop creating a new client for every request.

Fixes #19.

### CODE REVIEW

File: OSLC4Net_SDK/JsonProvider/JsonMediaTypeFormatter.cs [hunk 1]
```diff
@@ -270,6 +270,10 @@ IFormatterLogger formatterLogger
 
         try
         {
+            StreamReader sr = new(readStream);
```
Comment (berezovskyi) [inline OSLC4Net_SDK/JsonProvider/JsonMediaTypeFormatter.cs:273]: remove

File: OSLC4Net_SDK/OSLC4Net.Client/OslcRestClient.cs [hunk 2]
```diff
@@ -152,134 +166,144 @@ public sealed class OslcRestClient
...
+        return _client;
+    }
 
     /// <summary>
     /// Retrieve an OSLC resource of the specified type.  The type must have an associated .NET class with OSLC4Net annotations.
     /// </summary>
     /// <typeparam name="T"></typeparam>
     /// <returns></returns>
-	    public T GetOslcResource<T>() where T : class
+    public async Task<T> GetOslcResourceAsync<T>() where T : class, IResource
```
Comment (berezovskyi) [inline OSLC4Net_SDK/OSLC4Net.Client/OslcRestClient.cs:199]: document breaking changes

File: OSLC4Net_SDK/OSLC4Net.DotNetRdfProvider/RdfXmlMediaTypeFormatter.cs [hunk 3]
```diff
@@ -307,36 +308,49 @@ IFormatterLogger formatterLogger
...
             {
                 rdfParser = new RdfXmlParser();
             }
-            else if (content.Headers.ContentType.MediaType.Equals(OslcMediaType.TEXT_TURTLE))
+            else if (mediaType.Equals(OslcMediaType.TEXT_TURTLE))
             {
-                // TODO: enable RDF-star support (2023-09, Andrew)
-                rdfParser = new TurtleParser(TurtleSyntax.Original, true);
+                // TODO: make IRI validation configurable
+                rdfParser = new TurtleParser(TurtleSyntax.Rdf11Star, false);
```
Comment (berezovskyi) [inline OSLC4Net_SDK/OSLC4Net.DotNetRdfProvider/RdfXmlMediaTypeFormatter.cs:326]: note in changelog

**Comment by berezovskyi** [comment]
Tests are working against refimpl, other improvements will be done as separate PRs.
